### ISSUE TITLE
Issue on connect

### ISSUE THREAD

**Issue by jerkovicl** [dotnet/HttpRepl#345]
I did fresh installation of tool, tried to connect to api  (net core v2.1) via 
`https://localhost:44371 --swagger /swagger/v1/swagger.json`
and
`https://localhost:44371`
this is error i  get
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 119
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 119
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 103
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 119
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 119
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 103
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 119
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 103
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GenerateData(Schema schema) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 119
   at Microsoft.HttpRepl.OpenApi.SchemaDataGenerator.GetBodyString(IEnumerable`1 operation) in /_/src/Microsoft.HttpRepl/OpenApi/SchemaDataGenerator.cs:line 19
   at Microsoft.HttpRepl.OpenApi.ApiDefinitionReader.FillDirectoryInfo(DirectoryStructure parent, EndpointMetadata entry) in /_/src/Microsoft.HttpRepl/OpenApi/ApiDefinitionReader.cs:line 58
   at Microsoft.HttpRepl.OpenApi.SwaggerV2ApiDefinitionReader.ReadDefinition(JObject document, Uri sourceUri) in /_/src/Microsoft.HttpRepl/OpenApi/SwaggerV2ApiDefinitionReader.cs:line 112
   at Microsoft.HttpRepl.OpenApi.ApiDefinitionReader.Read(JObject document, Uri swaggerUri) in /_/src/Microsoft.HttpRepl/OpenApi/ApiDefinitionReader.cs:line 47
   at Microsoft.HttpRepl.ApiConnection.SetupApiDefinition(HttpState programState) in /_/src/Microsoft.HttpRepl/ApiConnection.cs:line 104
   at Microsoft.HttpRepl.ApiConnection.SetupHttpState(HttpState httpState, Boolean performAutoDetect, CancellationToken cancellationToken) in /_/src/Microsoft.HttpRepl/ApiConnection.cs:line 128
   at Microsoft.HttpRepl.Commands.ConnectCommand.ExecuteAsync(IShellState shellState, HttpState programState, DefaultCommandInput`1 commandInput, ICoreParseResult parseResult, CancellationToken cancellationToken) in /_/src/Microsoft.HttpRepl/Commands/ConnectCommand.cs:line 83
   at Microsoft.Repl.Commanding.DefaultCommandDispatcher`2.ExecuteCommandInternalAsync(IShellState shellState, CancellationToken cancellationToken) in /_/src/Microsoft.Repl/Commanding/DefaultCommandDispatcher.cs:line 150
   at Microsoft.Repl.Commanding.DefaultCommandDispatcher`2.ExecuteCommandAsync(IShellState shellState, CancellationToken cancellationToken) in /_/src/Microsoft.Repl/Commanding/DefaultCommandDispatcher.cs:line 113
```

**Comment by tlmii** [comment]
Hi @jerkovicl - it looks like something in the data schema in your swagger file is tripping up the parser. Would you be able to share your swagger file with us? Or at least the parts relevant to data schema/definitions so I can try to reproduce?

For some reason the line numbers in the stack trace don't match the ones in the file, but it looks like you've got a few levels of arrays of objects in your data definitions?

**Comment by jerkovicl** [comment]
> Hi @jerkovicl - it looks like something in the data schema in your swagger file is tripping up the parser. Would you be able to share your swagger file with us? Or at least the parts relevant to data schema/definitions so I can try to reproduce?
> 
> 
> 
> For some reason the line numbers in the stack trace don't match the ones in the file, but it looks like you've got a few levels of arrays of objects in your data definitions?

Sure I am gonna share swagger file tommorrow

**Comment by tlmii** [comment]
@jerkovicl sure - first name dot last name at microsoft dot com

**Comment by tlmii** [comment]
I got your swagger file and have started looking into it. It seems to have to do with following $ref's in the data definition. It seems to be ok with some of them (specifically where there is an array of objects and the objects are defined by arrays) but not others (where there is just an object defined by the $ref.

I'm suspicious about this line:

https://github.com/dotnet/HttpRepl/blob/85045582b5bd35ba8a09fd44cc1a05ee8e31472b/src/Microsoft.HttpRepl/OpenApi/SwaggerV2ApiDefinitionReader.cs#L75

meaning it was never implemented. But that doesn't explain why it seems to not care about the same thing in arrays.

I need to dig a little more.

**Comment by tlmii** [comment]
An update here - it looks like this is fixed in our CI builds of 5.0.0-preview now that the OpenAPI.NET work is in there. I'll ping this thread again once we have a preview up on nuget.

**Comment by tlmii** [comment]
@jerkovicl Apologies - I forgot to ping you here now that we have 5.0 preview builds available on nuget. Would you be able to give the new builds a shot to confirm the fix?

**Comment by jerkovicl** [comment]
@tlmii tried just now

```
 httprepl https://localhost:44371 --swagger /swagger/v1/swagger.json
(Disconnected)> connect https://localhost:44371 --swagger /swagger/v1/swagger.json
Using a base address of https://localhost:44371/
Unable to find an OpenAPI description
For detailed tool info, see https://aka.ms/http-repl-doc
```

**Comment by tlmii** [comment]
@jerkovicl hmm... Looks like this would be a good use case for #373 so we would know what was going on. I guess it's good the crash is gone, but... Not so helpful.

Is this the same swagger file you sent me before? Or has it changed since then?

**Comment by jerkovicl** [comment]
@tlmii you are developing verbose flag for better output as far as i understood from #373 .
Swagger file has changed yeah from the last time.

**Comment by tlmii** [comment]
@jerkovicl now that we have 5.0 released with the `--verbose` option from #373, can you try it again with that option and see if we get any better information?

**Comment by jerkovicl** [comment]
@tlmii tried
```
httprepl https://localhost:44371 --swagger /swagger/v1/swagger.json --verbose
(Disconnected)> connect https://localhost:44371 --swagger /swagger/v1/swagger.json --verbose
Checking https://localhost:44371/swagger/v1/swagger.json... The SSL connection could not be established, see inner exception.

Using a base address of https://localhost:44371/
Unable to find an OpenAPI description
```

**Comment by tlmii** [comment]
@jerkovicl so it looks like this is a different problem now - it can't read the swagger file because of ssl issues. I'm guessing self-signed certificate? Can you try trusting the cert and try again?

**Comment by jerkovicl** [comment]
@tlmii yes selfsigned i will try tmr with dotnet trust again

**Comment by tlmii** [comment]
@jerkovicl Just following up on this again to see if you've had any luck. Want to make sure you're unblocked.

**Comment by jerkovicl** [comment]
@tlmii sorry for the delay , yeah the -verbose flag did help got some warnings but its working now
